from . import hybrid
from . import vit

MODEL_MAPPING = {
    "VIT3_FC" : vit.VIT3_FC,
    "HYBRID_RESNET18_VITS_FC": hybrid.HYBRID_RESNET18_VITS_FC,
    "HYBRID_RESNET18_VIT4": hybrid.HYBRID_RESNET18_VIT4_FC,
    "HYBRID_RESNET18_VIT16": hybrid.HYBRID_RESNET18_VIT16_FC,
    "HYBRID_RESNET18_VIT24": hybrid.HYBRID_RESNET18_VIT24_FC,
}